apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: packet-capture
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: packet-capture
  template:
    metadata:
      labels:
        app: packet-capture
    spec:
      hostNetwork: true
      terminationGracePeriodSeconds: 60
      serviceAccountName: packet-capture
      containers:
        - name: controller
          image: packet-capture:dev
          imagePullPolicy: Never
          securityContext:
            privileged: true
            runAsUser: 0
            capabilities:
              add: ["NET_ADMIN", "NET_RAW"]
          env:
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: POD_NAME  
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          volumeMounts:
            - name: pcap-output
              mountPath: /outputs
      volumes:
        - name: pcap-output
          hostPath: 
            path: /var/log/packet-capture
            type: DirectoryOrCreate