apiVersion: v1
kind: Pod
metadata:
  name: test-ping
  namespace: default
  annotations:
    tcpdump.antrea.io: "5"
spec:
  containers:
  - name: busybox
    image: busybox
    command: ["sh", "-c", "while true; do ping 8.8.8.8; sleep 1; done"]